// Copyright ©2018 Christopher Boyd
//
// Generated by mdn-parser on 2018-07-19

using System;

namespace OpenNETCF.Web.UI
{
    /// <summary>
    /// Specifies the HTML tags that can be passed to an HtmlTextWriter object output stream.
    /// </summary>
    public enum HtmlTextWriterTag
    {
        /// <summary>
        /// The string passed as an HTML tag is not recognized.
        /// </summary>
        Unknown,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a">&lt;a&gt;</a>
        /// element (or anchor element) creates a hyperlink to other web pages, files, locations within
        /// the same page, email addresses, or any other URL.
        /// </summary>
        A,
        
        /// <summary>
        /// The HTML Abbreviation element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr">&lt;abbr&gt;</a>)
        /// represents an abbreviation or acronym; the optional title attribute can provide an expansion
        /// or description for the abbreviation.
        /// </summary>
        Abbr,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address">&lt;address&gt;</a>
        /// element indicates that the enclosed HTML provides contact information for a person or people,
        /// or for an organization.
        /// </summary>
        Address,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area">&lt;area&gt;</a>
        /// element defines a hot-spot region on an image, and optionally associates it with a hypertext
        /// link. This element is used only within a &lt;map&gt; element.
        /// </summary>
        Area,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article">&lt;article&gt;</a>
        /// element represents a self-contained composition in a document, page, application, or site,
        /// which is intended to be independently distributable or reusable (e.g., in syndication). Examples
        /// include: a forum post, a magazine or newspaper article, or a blog entry.
        /// </summary>
        Article,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside">&lt;aside&gt;</a>
        /// element represents a portion of a document whose content is only indirectly related to the
        /// document's main content.
        /// </summary>
        Aside,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio">&lt;audio&gt;</a>
        /// element is used to embed sound content in documents. It may contain one or more audio sources,
        /// represented using the src attribute or the &lt;source&gt; element: the browser will choose
        /// the most suitable one. It can also be the destination for streamed media, using a MediaStream.
        /// </summary>
        Audio,
        
        /// <summary>
        /// The HTML Bring Attention To element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b">&lt;b&gt;</a>) 
        /// is used to draw the reader's attention to the element's contents, which are not otherwise
        /// granted special importance.
        /// </summary>
        B,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base">&lt;base&gt;</a>
        /// element specifies the base URL to use for all relative URLs contained within a document.
        /// There can be only one &lt;base&gt; element in a document.
        /// </summary>
        Base,
        
        /// <summary>
        /// The HTML BiDirectional Isolation element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi">&lt;bdi&gt;</a>) 
        /// is used to indicate spans of text which might need to be rendered in the opposite direction
        /// than the surrounding text.
        /// </summary>
        Bdi,
        
        /// <summary>
        /// The HTML Bidirectional Text Override element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdo">&lt;bdo&gt;</a>)
        /// overrides the current directionality of text, so that the text within is rendered in a different
        /// direction.
        /// </summary>
        Bdo,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote">&lt;blockquote&gt;</a>
        /// Element (or HTML Block Quotation Element) indicates that the enclosed text is an extended
        /// quotation. Usually, this is rendered visually by indentation (see Notes for how to change
        /// it). A URL for the source of the quotation may be given using the cite attribute, while a
        /// text representation of the source can be given using the &lt;cite&gt; element.
        /// </summary>
        Blockquote,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body">&lt;body&gt;</a>
        /// Element represents the content of an HTML document. There can be only one &lt;body&gt; element
        /// in a document.
        /// </summary>
        Body,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br">&lt;br&gt;</a>
        /// element produces a line break in text (carriage-return). It is useful for writing a poem
        /// or an address, where the division of lines is significant.
        /// </summary>
        Br,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button">&lt;button&gt;</a>
        /// element represents a clickable button, which can be used in forms, or anywhere in a document
        /// that needs simple, standard button functionality.
        /// </summary>
        Button,
        
        /// <summary>
        /// Use the HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas">&lt;canvas&gt;</a>
        /// element with either the canvas scripting API or the WebGL API to draw graphics and animations.
        /// </summary>
        Canvas,
        
        /// <summary>
        /// The HTML Table Caption element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption">&lt;caption&gt;</a>)
        /// specifies the caption (or title) of a table, and if used is always the first child of a &lt;table&gt;.
        /// </summary>
        Caption,
        
        /// <summary>
        /// The HTML Citation element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite">&lt;cite&gt;</a>)
        /// is used to describe a reference to a cited creative work, and must include either the title
        /// or the URL of that work.
        /// </summary>
        Cite,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code">&lt;code&gt;</a>
        /// element displays its contents styled in a fashion intended to indicate that the text is a
        /// short fragment of computer code.
        /// </summary>
        Code,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col">&lt;col&gt;</a>
        /// element defines a column within a table and is used for defining common semantics on all
        /// common cells. It is generally found within a &lt;colgroup&gt; element.
        /// </summary>
        Col,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup">&lt;colgroup&gt;</a>
        /// element defines a group of columns within a table.
        /// </summary>
        Colgroup,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data">&lt;data&gt;</a>
        /// element links a given content with a machine-readable translation. If the content is time-
        /// or date-related, the &lt;time&gt; element must be used.
        /// </summary>
        Data,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist">&lt;datalist&gt;</a>
        /// element contains a set of &lt;option&gt; elements that represent the values available for
        /// other controls.
        /// </summary>
        Datalist,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd">&lt;dd&gt;</a>
        /// element provides the details about or the definition of the preceding term (&lt;dt&gt;) in
        /// a description list (&lt;dl&gt;).
        /// </summary>
        Dd,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del">&lt;del&gt;</a>
        /// element represents a range of text that has been deleted from a document.
        /// </summary>
        Del,
        
        /// <summary>
        /// The HTML Details Element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details">&lt;details&gt;</a>)
        /// creates a disclosure widget in which information is visible only when the widget is toggled
        /// into an "open" state.
        /// </summary>
        Details,
        
        /// <summary>
        /// The HTML Definition element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn">&lt;dfn&gt;</a>)
        /// is used to indicate the term being defined within the context of a definition phrase or sentence.
        /// </summary>
        Dfn,
        
        /// <summary>
        /// The HTML Content Division element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div">&lt;div&gt;</a>)
        /// is the generic container for flow content. It has no effect on the content or layout until
        /// styled using CSS.
        /// </summary>
        Div,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl">&lt;dl&gt;</a> element
        /// represents a description list. The element encloses a list of groups of terms (specified
        /// using the &lt;dt&gt; element) and descriptions (provided by &lt;dd&gt; elements). Common
        /// uses for this element are to implement a glossary or to display metadata (a list of key-value
        /// pairs).
        /// </summary>
        Dl,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dt">&lt;dt&gt;</a>
        /// element specifies a term in a description or definition list, and as such must be used inside
        /// a &lt;dl&gt; element.
        /// </summary>
        Dt,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em">&lt;em&gt;</a>
        /// element marks text that has stress emphasis. The &lt;em&gt; element can be nested, with each
        /// level of nesting indicating a greater degree of emphasis.
        /// </summary>
        Em,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed">&lt;embed&gt;</a>
        /// element embeds external content at the specified point in the document. This content is provided
        /// by an external application or other source of interactive content such as a browser plug-in.
        /// </summary>
        Embed,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset">&lt;fieldset&gt;</a>
        /// element is used to group several controls as well as labels (&lt;label&gt;) within a web
        /// form.
        /// </summary>
        Fieldset,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption">&lt;figcaption&gt;</a>
        /// element represents a caption or a legend associated with a figure or an illustration described
        /// by the rest of the data of the &lt;figure&gt; element which is its immediate ancestor.
        /// </summary>
        Figcaption,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure">&lt;figure&gt;</a>
        /// element represents self-contained content, frequently with a caption (&lt;figcaption&gt;),
        /// and is typically referenced as a single unit.
        /// </summary>
        Figure,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer">&lt;footer&gt;</a>
        /// element represents a footer for its nearest sectioning content or sectioning root element.
        /// A footer typically contains information about the author of the section, copyright data or
        /// links to related documents.
        /// </summary>
        Footer,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form">&lt;form&gt;</a>
        /// element represents a document section that contains interactive controls for submitting information
        /// to a web server.
        /// </summary>
        Form,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements">&lt;h1&gt;</a>–&lt;h6&gt;
        /// elements represent six levels of section headings. &lt;h1&gt; is the highest section level
        /// and &lt;h6&gt; is the lowest.
        /// </summary>
        H1,
        
        /// <summary>
        /// <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements">&lt;h2&gt;</a>
        /// </summary>
        H2,
        
        /// <summary>
        /// <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements">&lt;h3&gt;</a>
        /// </summary>
        H3,
        
        /// <summary>
        /// <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements">&lt;h4&gt;</a>
        /// </summary>
        H4,
        
        /// <summary>
        /// <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements">&lt;h5&gt;</a>
        /// </summary>
        H5,
        
        /// <summary>
        /// <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements">&lt;h6&gt;</a>
        /// </summary>
        H6,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head">&lt;head&gt;</a>
        /// element provides general information (metadata) about the document, including its title and
        /// links to its scripts and style sheets.
        /// </summary>
        Head,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header">&lt;header&gt;</a>
        /// element represents introductory content, typically a group of introductory or navigational
        /// aids. It may contain some heading elements but also other elements like a logo, a search
        /// form, an author name, and so on.
        /// </summary>
        Header,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr">&lt;hr&gt;</a>
        /// element represents a thematic break between paragraph-level elements (for example, a change
        /// of scene in a story, or a shift of topic with a section); historically, this has been presented
        /// as a horizontal rule or line.
        /// </summary>
        Hr,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html">&lt;html&gt;</a>
        /// element represents the root (top-level element) of an HTML document, so it is also referred
        /// to as the root element. All other elements must be descendants of this element.
        /// </summary>
        Html,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i">&lt;i&gt;</a>
        /// element represents a range of text that is set off from the normal text for some reason.
        /// Some examples include technical terms, foreign language phrases, or fictional character thoughts.
        /// It is typically displayed in italic type.
        /// </summary>
        I,
        
        /// <summary>
        /// The HTML Inline Frame element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe">&lt;iframe&gt;</a>)
        /// represents a nested browsing context, effectively embedding another HTML page into the current
        /// page.
        /// </summary>
        Iframe,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img">&lt;img&gt;</a>
        /// element embeds an image into the document.
        /// </summary>
        Img,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input">&lt;input&gt;</a>
        /// element is used to create interactive controls for web-based forms in order to accept data
        /// from the user.
        /// </summary>
        Input,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ins">&lt;ins&gt;</a>
        /// element represents a range of text that has been added to a document.
        /// </summary>
        Ins,
        
        /// <summary>
        /// The HTML Keyboard Input element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd">&lt;kbd&gt;</a>)
        /// represents a span of inline text denoting textual user input from a keyboard, voice input,
        /// or any other text entry device.
        /// </summary>
        Kbd,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label">&lt;label&gt;</a>
        /// element represents a caption for an item in a user interface.
        /// </summary>
        Label,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend">&lt;legend&gt;</a>
        /// element represents a caption for the content of its parent &lt;fieldset&gt;.
        /// </summary>
        Legend,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li">&lt;li&gt;</a>
        /// element is used to represent an item in a list. It must be contained in a parent element:
        /// an ordered list (&lt;ol&gt;), an unordered list (&lt;ul&gt;), or a menu (&lt;menu&gt;). In
        /// menus and unordered lists, list items are usually displayed using bullet points. In ordered
        /// lists, they are usually displayed with an ascending counter on the left, such as a number
        /// or letter.
        /// </summary>
        Li,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link">&lt;link&gt;</a>
        /// element specifies relationships between the current document and an external resource. This
        /// element is most commonly used to link to stylesheets.
        /// </summary>
        Link,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main">&lt;main&gt;</a>
        /// element represents the dominant content of the &lt;body&gt; of a document, portion of a document or
        /// application. The main content area consists of content that is directly related to or expands
        /// upon the central topic of a document, or the central functionality of an application.
        /// </summary>
        Main,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map">&lt;map&gt;</a>
        /// element is used with &lt;area&gt; elements to define an image map (a clickable link area).
        /// </summary>
        Map,
        
        /// <summary>
        /// The HTML Mark Text element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark">&lt;mark&gt;</a>)
        /// represents text which is marked or highlighted for reference or notation purposes, due to
        /// the marked passage's relevance or importance in the enclosing context.
        /// </summary>
        Mark,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu">&lt;menu&gt;</a>
        /// element represents a group of commands that a user can perform or activate. This includes
        /// both list menus, which might appear across the top of a screen, as well as context menus,
        /// such as those that might appear underneath a button after it has been clicked.
        /// </summary>
        Menu,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta">&lt;meta&gt;</a>
        /// element represents metadata that cannot be represented by other HTML meta-related elements,
        /// like &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt; or &lt;title&gt;.
        /// </summary>
        Meta,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter">&lt;meter&gt;</a>
        /// element represents either a scalar value within a known range or a fractional value.
        /// </summary>
        Meter,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav">&lt;nav&gt;</a>
        /// element represents a section of a page whose purpose is to provide navigation links, either
        /// within the current document or to other documents. Common examples of navigation sections
        /// are menus, tables of contents, and indexes.
        /// </summary>
        Nav,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript">&lt;noscript&gt;</a>
        /// element defines a section of HTML to be inserted if a script type on the page is unsupported
        /// or if scripting is currently turned off in the browser.
        /// </summary>
        Noscript,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object">&lt;object&gt;</a>
        /// element represents an external resource, which can be treated as an image, a nested browsing
        /// context, or a resource to be handled by a plugin.
        /// </summary>
        Object,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol">&lt;ol&gt;</a>
        /// element represents an ordered list of items, typically rendered as a numbered list.
        /// </summary>
        Ol,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup">&lt;optgroup&gt;</a>
        /// element creates a grouping of options within a &lt;select&gt; element.
        /// </summary>
        Optgroup,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option">&lt;option&gt;</a>
        /// element is used to define an item contained in a &lt;select&gt;, an &lt;optgroup&gt;, or
        /// a &lt;datalist&gt; element. As such, &lt;option&gt; can represent menu items in popups and
        /// other lists of items in an HTML document.
        /// </summary>
        Option,
        
        /// <summary>
        /// The HTML Output element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output">&lt;output&gt;</a>)
        /// is a container element into which a site or app can inject the results of a calculation or
        /// the outcome of a user action.
        /// </summary>
        Output,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p">&lt;p&gt;</a>
        /// element represents a paragraph of text.
        /// </summary>
        P,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/param">&lt;param&gt;</a>
        /// element defines parameters for an &lt;object&gt; element.
        /// </summary>
        Param,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture">&lt;picture&gt;</a>
        /// element serves as a container for zero or more &lt;source&gt; elements and one &lt;img&gt;
        /// element to provide versions of an image for different display device scenarios.
        /// </summary>
        Picture,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre">&lt;pre&gt;</a>
        /// element represents preformatted text which is to be presented exactly as written in the HTML
        /// file.
        /// </summary>
        Pre,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress">&lt;progress&gt;</a>
        /// element displays an indicator showing the completion progress of a task, typically displayed
        /// as a progress bar.
        /// </summary>
        Progress,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q">&lt;q&gt;</a>
        /// element  indicates that the enclosed text is a short inline quotation. Most modern browsers
        /// implement this by surrounding the text in quotation marks. 
        /// </summary>
        Q,
        
        /// <summary>
        /// The HTML Ruby Base (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb">&lt;rb&gt;</a>)
        /// element is used to delimit the base text component of a  &lt;ruby&gt; annotation, i.e. the
        /// text that is being annotated.
        /// </summary>
        Rb,
        
        /// <summary>
        /// The HTML Ruby Fallback Parenthesis (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rp">&lt;rp&gt;</a>)
        /// element is used to provide fall-back parentheses for browsers that do not support display
        /// of ruby annotations using the &lt;ruby&gt; element.
        /// </summary>
        Rp,
        
        /// <summary>
        /// The HTML Ruby Text (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rt">&lt;rt&gt;</a>)
        /// element specifies the ruby text component of a ruby annotation, which is used to provide
        /// pronunciation, translation, or transliteration information for East Asian typography. The
        /// &lt;rt&gt; element must always be contained within a &lt;ruby&gt; element.
        /// </summary>
        Rt,
        
        /// <summary>
        /// The HTML Ruby Text Container (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rtc">&lt;rtc&gt;</a>)
        /// element embraces semantic annotations of characters presented in a ruby of &lt;rb&gt; elements
        /// used inside of &lt;ruby&gt; element. &lt;rb&gt; elements can have both pronunciation (&lt;rt&gt;)
        /// and semantic (&lt;rtc&gt;) annotations.
        /// </summary>
        Rtc,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby">&lt;ruby&gt;</a>
        /// element represents a ruby annotation. Ruby annotations are for showing pronunciation of East
        /// Asian characters.
        /// </summary>
        Ruby,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s">&lt;s&gt;</a>
        /// element renders text with a strikethrough, or a line through it. Use the &lt;s&gt; element
        /// to represent things that are no longer relevant or no longer accurate. However, &lt;s&gt;
        /// is not appropriate when indicating document edits; for that, use the &lt;del&gt; and &lt;ins&gt;
        /// elements, as appropriate.
        /// </summary>
        S,
        
        /// <summary>
        /// The HTML Sample Element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/samp">&lt;samp&gt;</a>)
        /// is used to enclose inline text which represents sample (or quoted) output from a computer
        /// program.
        /// </summary>
        Samp,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script">&lt;script&gt;</a>
        /// element is used to embed or reference executable code; this is typically used to embed or
        /// refer to JavaScript code.
        /// </summary>
        Script,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section">&lt;section&gt;</a>
        /// element represents a standalone section — which doesn't have a more specific semantic element
        /// to represent it — contained within an HTML document.
        /// </summary>
        Section,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select">&lt;select&gt;</a>
        /// element represents a control that provides a menu of options:
        /// </summary>
        Select,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot">&lt;slot&gt;</a>
        /// element—part of the Web Components technology suite—is a placeholder inside a web component
        /// that you can fill with your own markup, which lets you create separate DOM trees and present
        /// them together.
        /// </summary>
        Slot,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/small">&lt;small&gt;</a>
        /// element makes the text font size one size smaller (for example, from large to medium, or
        /// from small to x-small) down to the browser's minimum font size.  In HTML5, this element is
        /// repurposed to represent side-comments and small print, including copyright and legal text,
        /// independent of its styled presentation.
        /// </summary>
        Small,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source">&lt;source&gt;</a>
        /// element specifies multiple media resources for the &lt;picture&gt;, the &lt;audio&gt; element,
        /// or the &lt;video&gt; element. It is an empty element. It is commonly used to serve the same
        /// media content in multiple formats supported by different browsers.
        /// </summary>
        Source,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span">&lt;span&gt;</a>
        /// element is a generic inline container for phrasing content, which does not inherently represent
        /// anything. It can be used to group elements for styling purposes (using the class or id attributes),
        /// or because they share attribute values, such as lang.
        /// </summary>
        Span,
        
        /// <summary>
        /// The HTML Strong Importance Element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong">&lt;strong&gt;</a>)
        /// indicates that its contents have strong importance, seriousness, or urgency. Browsers typically
        /// render the contents in bold type.
        /// </summary>
        Strong,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style">&lt;style&gt;</a>
        /// element contains style information for a document, or part of a document.
        /// </summary>
        Style,
        
        /// <summary>
        /// The HTML Subscript element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sub">&lt;sub&gt;</a>)
        /// specifies inline text which should be displayed as subscript for solely typographical reasons.
        /// </summary>
        Sub,
        
        /// <summary>
        /// The HTML Disclosure Summary element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary">&lt;summary&gt;</a>)
        /// element specifies a summary, caption, or legend for a &lt;details&gt; element's disclosure
        /// box.
        /// </summary>
        Summary,
        
        /// <summary>
        /// The HTML Superscript element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup">&lt;sup&gt;</a>)
        /// specifies inline text which is to be displayed as superscript for solely typographical reasons.
        /// </summary>
        Sup,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table">&lt;table&gt;</a>
        /// element represents tabular data — that is, information presented in a two-dimensional table
        /// comprised of rows and columns of cells containing data.
        /// </summary>
        Table,
        
        /// <summary>
        /// The HTML Table Body element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody">&lt;tbody&gt;</a>)
        /// encapsulates a set of table row (&lt;tr&gt; elements, indicating that they comprise the body
        /// of the table (&lt;table&gt;).
        /// </summary>
        Tbody,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td">&lt;td&gt;</a>
        /// element defines a cell of a table that contains data. It participates in the table model.
        /// </summary>
        Td,
        
        /// <summary>
        /// The HTML Content Template (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template">&lt;template&gt;</a>)
        /// element is a mechanism for holding client-side content that is not to be rendered when a
        /// page is loaded but may subsequently be instantiated during runtime using JavaScript.
        /// </summary>
        Template,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea">&lt;textarea&gt;</a>
        /// element represents a multi-line plain-text editing control, useful when you want to allow
        /// users to enter a sizeable amount of free-form text, for example a comment on a review or
        /// feedback form.
        /// </summary>
        Textarea,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot">&lt;tfoot&gt;</a>
        /// element defines a set of rows summarizing the columns of the table.
        /// </summary>
        Tfoot,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th">&lt;th&gt;</a>
        /// element defines a cell as header of a group of table cells. The exact nature of this group
        /// is defined by the scope and headers attributes.
        /// </summary>
        Th,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead">&lt;thead&gt;</a>
        /// element defines a set of rows defining the head of the columns of the table.
        /// </summary>
        Thead,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time">&lt;time&gt;</a>
        /// element represents a specific period in time. It may include the datetime attribute to translate
        /// dates into machine-readable format, allowing for better search engine results or custom features
        /// such as reminders.
        /// </summary>
        Time,
        
        /// <summary>
        /// The HTML Title element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title">&lt;title&gt;</a>)
        /// defines the document's title that is shown in a browser's title bar or a page's tab.
        /// </summary>
        Title,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr">&lt;tr&gt;</a>
        /// element defines a row of cells in a table. The row's cells can then be established using
        /// a mix of &lt;td&gt; (data cell) and &lt;th&gt; (header cell) elements.The HTML &lt;tr&gt;
        /// element specifies that the markup contained inside the &lt;tr&gt; block comprises one row
        /// of a table, inside which the &lt;th&gt; and &lt;td&gt; elements create header and data cells,
        /// respectively, within the row.
        /// </summary>
        Tr,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track">&lt;track&gt;</a>
        /// element is used as a child of the media elements &lt;audio&gt; and &lt;video&gt;. It lets
        /// you specify timed text tracks (or time-based data), for example to automatically handle subtitles.
        /// The tracks are formatted in WebVTT format (.vtt files) — Web Video Text Tracks or Timed Text
        /// Markup Language (TTML).
        /// </summary>
        Track,
        
        /// <summary>
        /// The HTML Unarticulated Annotation element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u">&lt;u&gt;</a>)
        /// represents a span of inline text which should be rendered in a way that indicates that it
        /// has a non-textual annotation.
        /// </summary>
        U,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul">&lt;ul&gt;</a>
        /// element represents an unordered list of items, typically rendered as a bulleted list.
        /// </summary>
        Ul,
        
        /// <summary>
        /// The HTML Variable element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var">&lt;var&gt;</a>)
        /// represents the name of a variable in a mathematical expression or a programming context.
        /// </summary>
        Var,
        
        /// <summary>
        /// The HTML Video element (<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video">&lt;video&gt;</a>)
        /// embeds a media player which supports video playback into the document.
        /// </summary>
        Video,
        
        /// <summary>
        /// The HTML <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr">&lt;wbr&gt;</a>
        /// element represents a word break opportunity—a position within text where the browser may
        /// optionally break a line, though its line-breaking rules would not otherwise create a break
        /// at that location.
        /// </summary>
        Wbr,
        
    }
}
